INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Medellín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Abejorral');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Abriaquí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Alejandría');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Amagá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Amalfi');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Andes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Angelópolis');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Angostura');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Anorí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tununguá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Anza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Apartadó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Arboletes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Argelia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Armenia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Barbosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Bello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Betania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Betulia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Ciudad Bolívar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Briceño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Buriticá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Cáceres');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Caicedo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Caldas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Campamento');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Cañasgordas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Caracolí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Caramanta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Carepa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Motavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Carolina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Caucasia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Chigorodó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Cisneros');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Cocorná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Concepción');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Concordia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Copacabana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Dabeiba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Don Matías');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Ebéjico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','El Bagre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Entrerrios');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Envigado');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Fredonia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San Bernardo del Viento');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Giraldo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Girardota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Gómez Plata');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Istmina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Guadalupe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Guarne');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Guatapé');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Heliconia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Hispania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Itagui');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Ituango');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Belmira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Jericó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','La Ceja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','La Estrella');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','La Pintada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','La Unión');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Liborina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Maceo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Marinilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Montebello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Murindó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Mutatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Nariño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Necoclí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Nechí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Olaya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Peñol');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Peque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Pueblorrico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Puerto Berrío');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Puerto Nare');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Puerto Triunfo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Remedios');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Retiro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Rionegro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Sabanalarga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Sabaneta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Salgar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Ciénega');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Santacruz');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Francisco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Jerónimo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Puerto Wilches');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Puerto Parra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Luis');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Pedro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Rafael');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Roque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Vicente');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Santa Bárbara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Santo Domingo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','El Santuario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Segovia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Sopetrán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Uribe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Támesis');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Tarazá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Tarso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Titiribí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Toledo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Turbo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Uramita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Urrao');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Valdivia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Valparaíso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Vegachí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Venecia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Yalí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Yarumal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Yolombó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Yondó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Zaragoza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Barranquilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Baranoa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Candelaria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Galapa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Luruaco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Malambo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Manatí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Piojó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Polonuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Sabanagrande');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Sabanalarga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Santa Lucía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Santo Tomás');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Soledad');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Suan');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Tubará');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Usiacurí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Achí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Arenal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Arjona');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Arroyohondo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Calamar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Cantagallo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Cicuco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Córdoba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Clemencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','El Guamo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Magangué');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Mahates');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Margarita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Montecristo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Mompós');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Morales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Norosí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Pinillos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Regidor');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Río Viejo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Estanislao');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Fernando');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Juan Nepomuceno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Santa Catalina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Santa Rosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Simití');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Soplaviento');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Talaigua Nuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Tiquisio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Turbaco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Turbaná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Villanueva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tunja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Almeida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Aquitania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Arcabuco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Berbeo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Betéitiva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Boavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Boyacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Briceño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Buena Vista');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Busbanzá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Caldas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Campohermoso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Cerinza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chinavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chiquinquirá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chiscas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chitaraque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chivatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Cómbita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Coper');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Corrales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Covarachía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Cubará');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Cucaita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Cuítiva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chíquiza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Chivor');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Duitama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','El Cocuy');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','El Espino');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Firavitoba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Floresta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Gachantivá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Gameza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Garagoa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Guacamayas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Guateque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Guayatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Güicán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Iza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Jenesano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Jericó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Labranzagrande');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','La Capilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','La Victoria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Macanal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Maripí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Miraflores');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Mongua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Monguí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Moniquirá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Muzo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Nobsa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Nuevo Colón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Oicatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Otanche');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Pachavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Páez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Paipa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Pajarito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Panqueba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Pauna');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Paya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Pesca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Pisba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Puerto Boyacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Quípama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Ramiriquí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Ráquira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Rondón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Saboyá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sáchica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Samacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San Eduardo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San Mateo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Santana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Santa María');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Santa Sofía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sativanorte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sativasur');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Siachoque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Soatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Socotá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Socha');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sogamoso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Somondoco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sora');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sotaquirá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Soracá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Susacón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sutamarchán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Sutatenza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tasco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tenza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tibaná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tinjacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tipacoque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Toca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tópaga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Turmequé');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tutazá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Umbita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Ventaquemada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Viracachá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Zetaquira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Manizales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Aguadas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Anserma');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Aranzazu');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Belalcázar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Chinchiná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Filadelfia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','La Dorada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','La Merced');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Manzanares');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Marmato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Marulanda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Neira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Norcasia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Pácora');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Palestina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Pensilvania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Riosucio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Risaralda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Salamina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Samaná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','San José');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Supía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Victoria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Villamaría');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Viterbo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Florencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Albania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Curillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','El Doncello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','El Paujil');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Morelia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Puerto Rico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Solano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Solita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Valparaíso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Popayán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Almaguer');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Argelia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Balboa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Bolívar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Buenos Aires');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Cajibío');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Caldono');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Caloto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Corinto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','El Tambo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Florencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Guachené');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Guapi');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Inzá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Jambaló');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','La Sierra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','La Vega');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','López');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Mercaderes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Miranda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Morales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Padilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Patía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Piamonte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Piendamó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Puerto Tejada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Puracé');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Rosas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Santa Rosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Silvia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Sotara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Suárez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Sucre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Timbío');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Timbiquí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Toribio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Totoró');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Villa Rica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Valledupar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Aguachica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Agustín Codazzi');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Astrea');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Becerril');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Bosconia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Chimichagua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Chiriguaná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Curumaní');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','El Copey');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','El Paso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Gamarra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','González');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','La Gloria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Manaure');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Pailitas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Pelaya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Pueblo Bello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','La Paz');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','San Alberto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','San Diego');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','San Martín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Tamalameque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Montería');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Ayapel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Buenavista');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Canalete');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Cereté');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Chimá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Chinú');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Cotorra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Lorica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Los Córdobas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Momil');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Moñitos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Planeta Rica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Pueblo Nuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Puerto Escondido');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Purísima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Sahagún');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San Andrés Sotavento');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San Antero');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San Pelayo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Tierralta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Tuchín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Valencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Anapoima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Arbeláez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Beltrán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Bituima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Bojacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cabrera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cachipay');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cajicá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Caparrapí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Caqueza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Chaguaní');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Chipaque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Choachí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Chocontá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cogua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Cucunubá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','El Colegio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','El Rosal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Fomeque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Fosca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Funza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Fúquene');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Gachala');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Gachancipá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Gachetá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Girardot');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Granada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guachetá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guaduas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guasca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guataquí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guatavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guayabetal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Gutiérrez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Jerusalén');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Junín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','La Calera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','La Mesa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','La Palma');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','La Peña');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','La Vega');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Lenguazaque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Macheta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Madrid');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Manta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Medina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Mosquera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Nariño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Nemocón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Nilo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Nimaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Nocaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Venecia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Pacho');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Paime');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Pandi');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Paratebueno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Pasca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Puerto Salgar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Pulí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Quebradanegra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Quetame');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Quipile');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Apulo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Ricaurte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','San Bernardo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','San Cayetano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','San Francisco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Sesquilé');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Sibaté');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Silvania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Simijaca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Soacha');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Subachoque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Suesca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Supatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Susa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Sutatausa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tabio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tausa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tena');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tenjo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tibacuy');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tibirita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tocaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Tocancipá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Topaipí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Ubalá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Ubaque');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Une');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Útica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Vianí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Villagómez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Villapinzón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Villeta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Viotá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Zipacón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Quibdó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Acandí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Alto Baudo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Atrato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Bagadó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Bahía Solano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Bajo Baudó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Bojaya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Cértegui');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Condoto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Juradó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Lloró');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Medio Atrato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Medio Baudó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Medio San Juan');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Nóvita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Nuquí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Río Iro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Río Quito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Riosucio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Sipí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Unguía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Neiva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Acevedo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Agrado');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Aipe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Algeciras');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Altamira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Baraya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Campoalegre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Colombia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Elías');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Garzón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Gigante');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Guadalupe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Hobo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Iquira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Isnos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','La Argentina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','La Plata');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Nátaga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Oporapa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Paicol');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Palermo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Palestina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Pital');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Pitalito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Rivera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Saladoblanco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Santa María');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Suaza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Tarqui');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Tesalia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Tello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Teruel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Timaná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Villavieja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','Yaguará');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Riohacha');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Albania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Barrancas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Dibula');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Distracción');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','El Molino');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Fonseca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Hatonuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Maicao');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Manaure');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Uribia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Urumita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','Villanueva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Santa Marta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Algarrobo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Aracataca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Ariguaní');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Cerro San Antonio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Chivolo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Concordia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','El Banco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','El Piñon');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','El Retén');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Fundación');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Guamal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Nueva Granada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Pedraza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Pivijay');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Plato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Remolino');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Salamina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','San Zenón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Santa Ana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Sitionuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Tenerife');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Zapayán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Zona Bananera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Villavicencio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Acacias');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Cabuyaro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Cubarral');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Cumaral');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','El Calvario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','El Castillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','El Dorado');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Granada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Guamal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Mapiripán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Mesetas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','La Macarena');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Lejanías');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Puerto Concordia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Puerto Gaitán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Puerto López');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Puerto Lleras');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Puerto Rico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Restrepo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','San Juanito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','San Martín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Vista Hermosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Pasto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Albán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Aldana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Ancuyá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Barbacoas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Colón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Consaca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Contadero');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Córdoba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Cuaspud');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Cumbal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Cumbitara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','El Charco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','El Peñol');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','El Rosario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','El Tambo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Funes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Guachucal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Guaitarilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Gualmatán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Iles');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Imués');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Ipiales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','La Cruz');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','La Florida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','La Llanada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','La Tola');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','La Unión');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Leiva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Linares');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Los Andes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Magüí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Mallama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Mosquera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Nariño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Olaya Herrera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Ospina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Francisco Pizarro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Policarpa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Potosí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Providencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Puerres');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Pupiales');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Ricaurte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Roberto Payán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Samaniego');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Sandoná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','San Bernardo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','San Lorenzo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','San Pablo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Santa Bárbara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Sapuyes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Taminango');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Tangua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Túquerres');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Yacuanquer');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Armenia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Buenavista');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Circasia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Córdoba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Filandia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','La Tebaida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Montenegro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Pijao');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Quimbaya');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Salento');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Pereira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Apía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Balboa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Dosquebradas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Guática');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','La Celia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','La Virginia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Marsella');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Mistrató');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Pueblo Rico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Quinchía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Santuario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Bucaramanga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Aguada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Albania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Aratoca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Barbosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Barichara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Barrancabermeja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Betulia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Bolívar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Cabrera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','California');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Carcasí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Cepitá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Cerrito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Charalá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Charta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Chipatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Cimitarra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Concepción');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Confines');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Contratación');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Coromoro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Curití');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','El Guacamayo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','El Playón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Encino');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Enciso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Florián');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Floridablanca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Galán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Gambita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Girón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Guaca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Guadalupe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Guapotá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Guavatá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Güepsa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Jesús María');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Jordán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','La Belleza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Landázuri');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','La Paz');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Lebríja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Los Santos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Macaravita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Málaga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Matanza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Mogotes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Molagavita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Ocamonte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Oiba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Onzaga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Palmar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Páramo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Piedecuesta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Pinchote');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Puente Nacional');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Rionegro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Andrés');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Gil');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Joaquín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Miguel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Santa Bárbara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Simacota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Socorro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Suaita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Sucre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Suratá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Tona');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Vélez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Vetas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Villanueva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Zapatoca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Sincelejo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Buenavista');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Caimito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Coloso');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Coveñas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Chalán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','El Roble');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Galeras');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Guaranda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','La Unión');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Los Palmitos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Majagual');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Morroa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Ovejas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Palmito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Benito Abad');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Marcos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Onofre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Pedro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Sucre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Tolú Viejo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Alpujarra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Alvarado');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Ambalema');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Armero');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Ataco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Cajamarca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Chaparral');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Coello');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Coyaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Cunday');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Dolores');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Espinal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Falan');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Flandes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Fresno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Guamo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Herveo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Honda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Icononzo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Mariquita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Melgar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Murillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Natagaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Ortega');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Palocabildo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Piedras');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Planadas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Prado');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Purificación');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Rio Blanco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Roncesvalles');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Rovira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Saldaña');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Santa Isabel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Venadillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Villahermosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Villarrica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Arauquita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Cravo Norte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Fortul');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Puerto Rondón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Saravena');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Tame');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Arauca','Arauca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Yopal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Aguazul');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Chámeza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Hato Corozal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','La Salina');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Monterrey');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Pore');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Recetor');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Sabanalarga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Sácama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Tauramena');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Trinidad');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Villanueva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Mocoa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Colón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Orito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Puerto Caicedo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Puerto Guzmán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Leguízamo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Sibundoy');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','San Francisco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','San Miguel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Santiago');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Leticia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','El Encanto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','La Chorrera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','La Pedrera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','La Victoria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Puerto Arica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Puerto Nariño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Puerto Santander');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Tarapacá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Inírida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Barranco Minas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Mapiripana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','San Felipe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Puerto Colombia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','La Guadalupe');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Cacahual');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Pana Pana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Mitú');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Carurú');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Taraira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Papunahua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Yavaraté');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vaupés','Pacoa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guainía','Morichal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vichada','Puerto Carreño');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vichada','La Primavera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vichada','Santa Rosalía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Vichada','Cumaribo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','San José del Fragua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Barranca de Upía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Palmas del Socorro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','San Juan de Río Seco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Juan de Acosta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Fuente de Oro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','San Luis de Gaceno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','El Litoral del San Juan');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Villa de San Diego de Ubate');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Barranco de Loba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Togüí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Santa Rosa del Sur');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','El Cantón del San Pablo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Villa de Leyva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','San Sebastián de Buenavista');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Paz de Río');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Hatillo de Loba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Sabanas de San Angel');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guaviare','Calamar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','Río de Oro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Pedro de Uraba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guaviare','San José del Guaviare');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Santa Rosa de Viterbo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Santander de Quilichao');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guaviare','Miraflores');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Santafé de Antioquia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','San Carlos de Guaroa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Palmar de Varela');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Santa Rosa de Osos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Andrés de Cuerquía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Valle de San Juan');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Vicente de Chucurí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San José de Miranda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Archipiélago de San Andrés, Providencia y Santa Catalina','Providencia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Santa Rosa de Cabal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Guayabal de Siquima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Belén de Los Andaquies');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Paz de Ariporo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Santa Helena del Opón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San Pablo de Borbur');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','La Jagua del Pilar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cesar','La Jagua de Ibirico');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Luis de Sincé');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San Luis de Gaceno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','El Carmen de Bolívar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','El Carmen de Atrato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','San Juan de Betulia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Pijiño del Carmen');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Vigía del Fuerte');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Martín de Loba');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Altos del Rosario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Carmen de Apicala');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','San Antonio del Tequendama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Sabana de Torres');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Guaviare','El Retorno');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San José de Uré');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','San Pedro de Cartago');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Campo de La Cruz');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','San Juan de Arama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San José de La Montaña');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Cartagena del Chairá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','San José del Palmar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Agua de Dios');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Jacinto del Cauca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Huila','San Agustín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','El Tablón de Gómez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Archipiélago de San Andrés, Providencia y Santa Catalina','San Andrés');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San José de Pare');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Valle de Guamez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Pablo de Borbur');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Santiago de Tolú');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bogotá D.C.','Bogotá D.C.');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Carmen de Carupa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Ciénaga de Oro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Juan de Urabá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('La Guajira','San Juan del Cesar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','El Carmen de Chucurí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','El Carmen de Viboral');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Risaralda','Belén de Umbría');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Belén de Bajira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Valle de San José');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','San Luis');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','San Miguel de Sema');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','San Antonio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','San Benito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Vergara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','San Carlos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Puerto Alegría');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Hato');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Jacinto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','San Sebastián');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','San Carlos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tuta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Silos');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Cácota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','El Dovio');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Toledo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Roldanillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Mutiscua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Argelia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','El Zulia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Salazar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Sevilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Zarzal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Cucutilla');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','El Cerrito');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Cartago');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Caicedonia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Puerto Santander');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Gramalote');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','El Cairo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','El Tarra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','La Unión');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Restrepo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Teorama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Dagua');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Arboledas');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Guacarí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Lourdes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Ansermanuevo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Bochalema');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Bugalagrande');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Convención');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Hacarí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','La Victoria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Herrán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Ginebra');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Yumbo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Obando');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Tibú');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','San Cayetano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','San Calixto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Bolívar');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','La Playa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Cali');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','San Pedro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Guadalajara de Buga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Chinácota');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Ragonvalia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','La Esperanza');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Villa del Rosario');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Chitagá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Calima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Sardinata');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Andalucía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Pradera');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Abrego');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Los Patios');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Ocaña');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Bucarasica');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Yotoco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Palmira');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Riofrío');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Santiago');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Alcalá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Versalles');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Labateca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Cachirá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Villa Caro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Durania');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','El Águila');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Toro');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Candelaria');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','La Cumbre');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Ulloa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Trujillo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Vijes');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Chimá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Sampués');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Nunchía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Pamplona');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Albán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Montelíbano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Puerto Asís');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Sucre','Corozal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Buesaco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Maní');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','El Peñón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Tuluá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Casabianca');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Anolaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Chía');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','San Andrés de Tumaco');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','Milán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','Capitanejo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Anzoátegui');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Florida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Repelón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Frontino');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','El Peñón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Pamplonita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Amazonas','Miriti Paraná');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Támara');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Tibasosa');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cauca','Páez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Ibagué');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Puerto Colombia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Belén');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Sopó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Carmen del Darien');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Gama');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Sasaima');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Chachagüí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','Cúcuta');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Cartagena');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Granada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Santa Bárbara de Pinto');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','María la Baja');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','La Montañita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caquetá','San Vicente del Caguán');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Santander','El Peñón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Jardín');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Jamundí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Tadó');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Casanare','Orocué');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Líbano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Yacopí');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Calarcá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Antioquia','Sonsón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Norte de Santander','El Carmen');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Lérida');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','La Apartada');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','San Cristóbal');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Fusagasugá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Bolívar','Zambrano');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','La Uvita');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Zipaquirá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Quindío','Génova');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Tolima','Suárez');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Meta','Castilla la Nueva');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Boyacá','Belén');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Chocó','Unión Panamericana');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Pueblo Viejo');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Putumayo','Villagarzón');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Cundinamarca','Facatativá');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Córdoba','Puerto Libertador');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Caldas','Marquetalia');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Nariño','Arboleda');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Valle del Cauca','Buenaventura');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Magdalena','Ciénaga');
INSERT INTO ciudad(departamento,ciudad) VALUES ('Atlántico','Ponedera');
